apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: webrobot

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app: webrobot-portal
  version: v1.0.0

