apiVersion: v1
kind: Service
metadata:
  name: webrobot-portal-service
  namespace: webrobot
  labels:
    app: webrobot-portal
    service: portal
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: webrobot-portal
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800

